package com.teamspace.android.utils;

public class Constants {
	
	public static final String EMPLOYEE_ID = "EMPLOYEE_ID";
    public static final String DEEPLINK = "DEEPLINK";
    public static final String IS_FROM_PUSH = "IS_FROM_PUSH";
    public static final String TASK_CREATION = "TASK_CREATION";
    public static final String EMP_CREATION = "EMP_CREATION";
	public static final String TASK_ID = "TASK_ID";
    public static final String TASK_ARRAY = "TASK_ARRAY";
    public static final String USER_ID = "USER_ID";
    public static final String SERVER_IP = "SERVER_IP";
    public static final String SERVER_PORT = "SERVER_PORT";
    public static final String USER_KEY = "USER_KEY";
	public static final String TASK_TITLE = "TASK_TITLE";
	public static final String EMPLOYEE_NAME = "EMPLOYEE_NAME";
    public static final String FILTERED_EMP_ID = "FILTERED_EMP_ID";
	public static final String EMPLOYEE_PHONE = "EMPLOYEE_PHONE";
	public static final String HIDE_KEYBOARD = "HIDE_KEYBOARD";
	public static final String EMPTY_STRING = "";
	public static final String EMPLOYEE = "Employee";
	public static final String KEY = "key";
    public static final String CACHE_BUSTER = "cb";
	public static final long DAILY = 86400;
	public static final long WEEKLY = 86400 * 7;
	public static final long BIWEEKLY = 86400 * 14;
	public static final long MONTHLY = 86400 * 30;
	public static final String DAILY_STR = "Daily";
	public static final String WEEKLY_STR = "Weekly";
	public static final String BIWEEKLY_STR = "Biweekly";
	public static final String MONTHLY_STR = "Monthly";
	public static final String OPEN = "open";
	public static final String CLOSED = "closed";
	public static final String FREQUENCY = "FREQUENCY";	
	public static final String DETAILS = "DETAILS";
    public static final String NOTIF_SENT = "NOTIF_SENT";
    public static final String REFRESH_ALL_TASKS = "REFRESH_ALL_TASKS";
    public static final String REFRESH_EMP = "REFRESH_EMP";
    public static final String REFRESH_MSG = "REFRESH_MSG";
    public static final String FRESH_LOGIN = "FRESH_LOGIN";
    public static final String LAUNCH_ON_TOP = "LAUNCH_ON_TOP";
    public static final String USERID = "userID";
    public static final String SERVER_CODE = "serverCode";
    public static final String SERVER_RESPONSE = "serverResponse";
    public static final String URL = "url";
    public static final String DESCRIPTION = "desc";
    public static final String USER_PHONE = "phone";
    public static final String EMPLOYEE_DRAFT = "EMPLOYEE_DRAFT_";
}
